services:
  techfood.api:
    image: ${DOCKER_REGISTRY-}techfoodapi
    build:
      context: .
      dockerfile: src/TechFood.Api/Dockerfile
    container_name: techfood.api
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      ConnectionStrings__DataBaseConection: Server=dbsqlserver;Database=dbtechfood;User Id=sa;Password=123456#4EA;TrustServerCertificate=True;
    depends_on:
      - dbsqlserver
  dbsqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: dbsqlserver
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "123456#4EA"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
volumes:
  sqlserver_data:
