@rootUrl=https://localhost:44310/v1

### Create Order
POST {{rootUrl}}/orders/
Content-Type: application/json

{
    "customerId": "25b58f54-63bc-42da-8cf6-8162097e72c8",
    "cuponCode": null,
    "items": [
        {
            "productId": "090d8eb0-f514-4248-8512-cf0d61a262f0",
            "quantity": 2
        },
        {
            "productId": "55f32e65-c82f-4a10-981c-cdb7b0d2715a",
            "quantity": 1
        }
    ]
}

### Prepare Order
POST {{rootUrl}}/orders/963d122b-72c4-42ec-9e37-5953322931f9/prepare

### Finish Order
POST {{rootUrl}}/orders/963d122b-72c4-42ec-9e37-5953322931f9/finish
