apiVersion: v1
kind: ConfigMap
metadata:
  name: techfood-api-config
  namespace: techfood
  labels:
    app.kubernetes.io/name: techfood-api
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: techfood-system
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_HTTP_PORTS: "8080"
  TechFoodStaticImagesUrl: "/static-images"
  AllowedHosts: "*"
  Jwt__Issuer: "techfood-jwts"
  Jwt__Audience: "techfood"
  Payments__MercadoPago__UserId: "2414323212"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: techfood
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: techfood-system
data:
  default.conf: |
    upstream admin_upstream {
        server techfood-admin-service:80;
    }

    upstream self_order_upstream {
        server techfood-self-order-service:80;
    }

    upstream monitor_upstream {
        server techfood-monitor-service:80;
    }

    upstream api_upstream {
        server techfood-api-service:8080;
    }

    server {
        listen 5000;
        
        location /admin {
            proxy_pass http://admin_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /self-order {
            proxy_pass http://self_order_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /monitor {
            proxy_pass http://monitor_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /api {
            proxy_pass http://api_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /health {
            proxy_pass http://api_upstream/health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        location /static-images {
            proxy_pass http://api_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
